// Words for reading practice, written in kana only.
//
// Every word here is spelled using nothing but the 46 basic hiragana and the 25
// dakuten characters, so you never meet a character the app has not taught you.
// That rules out anything needing the small っ or ゃ ゅ ょ - so no がっこう and no
// でんしゃ - until those are added as their own set.
//
// Which set a word belongs to is worked out in code from its characters, not
// tagged by hand, so it cannot drift out of step. A word is offered in a set only
// when every one of its characters is taught by that set.

var WORDS = [
  // --- animals and nature ---
  { kana: 'ねこ',     romaji: 'neko',      meaning: 'cat' },
  { kana: 'いぬ',     romaji: 'inu',       meaning: 'dog' },
  { kana: 'とり',     romaji: 'tori',      meaning: 'bird' },
  { kana: 'さかな',   romaji: 'sakana',    meaning: 'fish' },
  { kana: 'うま',     romaji: 'uma',       meaning: 'horse' },
  { kana: 'うし',     romaji: 'ushi',      meaning: 'cow' },
  { kana: 'ぶた',     romaji: 'buta',      meaning: 'pig' },
  { kana: 'うさぎ',   romaji: 'usagi',     meaning: 'rabbit' },
  { kana: 'とかげ',   romaji: 'tokage',    meaning: 'lizard' },
  { kana: 'どうぶつ', romaji: 'doubutsu',  meaning: 'animal' },
  { kana: 'やま',     romaji: 'yama',      meaning: 'mountain' },
  { kana: 'かわ',     romaji: 'kawa',      meaning: 'river' },
  { kana: 'うみ',     romaji: 'umi',       meaning: 'sea' },
  { kana: 'そら',     romaji: 'sora',      meaning: 'sky' },
  { kana: 'ほし',     romaji: 'hoshi',     meaning: 'star' },
  { kana: 'つき',     romaji: 'tsuki',     meaning: 'moon' },
  { kana: 'はな',     romaji: 'hana',      meaning: 'flower' },
  { kana: 'くさ',     romaji: 'kusa',      meaning: 'grass' },
  { kana: 'き',       romaji: 'ki',        meaning: 'tree' },
  { kana: 'みず',     romaji: 'mizu',      meaning: 'water' },
  { kana: 'あめ',     romaji: 'ame',       meaning: 'rain' },
  { kana: 'ゆき',     romaji: 'yuki',      meaning: 'snow' },
  { kana: 'かぜ',     romaji: 'kaze',      meaning: 'wind' },
  { kana: 'ひまわり', romaji: 'himawari',  meaning: 'sunflower' },
  { kana: 'はなび',   romaji: 'hanabi',    meaning: 'fireworks' },
  { kana: 'にじ',     romaji: 'niji',      meaning: 'rainbow' },

  // --- time ---
  { kana: 'はる',     romaji: 'haru',      meaning: 'spring' },
  { kana: 'なつ',     romaji: 'natsu',     meaning: 'summer' },
  { kana: 'あき',     romaji: 'aki',       meaning: 'autumn' },
  { kana: 'ふゆ',     romaji: 'fuyu',      meaning: 'winter' },
  { kana: 'あさ',     romaji: 'asa',       meaning: 'morning' },
  { kana: 'ひる',     romaji: 'hiru',      meaning: 'daytime, noon' },
  { kana: 'よる',     romaji: 'yoru',      meaning: 'night' },
  { kana: 'きのう',   romaji: 'kinou',     meaning: 'yesterday' },
  { kana: 'あした',   romaji: 'ashita',    meaning: 'tomorrow' },
  { kana: 'ことし',   romaji: 'kotoshi',   meaning: 'this year' },
  { kana: 'まいにち', romaji: 'mainichi',  meaning: 'every day' },
  { kana: 'じかん',   romaji: 'jikan',     meaning: 'time, an hour' },
  { kana: 'さんぽ',   romaji: 'sanpo',     meaning: 'a walk, a stroll' },

  // --- people ---
  { kana: 'ひと',     romaji: 'hito',      meaning: 'person' },
  { kana: 'おとこ',   romaji: 'otoko',     meaning: 'man' },
  { kana: 'おんな',   romaji: 'onna',      meaning: 'woman' },
  { kana: 'こども',   romaji: 'kodomo',    meaning: 'child' },
  { kana: 'ちち',     romaji: 'chichi',    meaning: 'father' },
  { kana: 'はは',     romaji: 'haha',      meaning: 'mother' },
  { kana: 'あに',     romaji: 'ani',       meaning: 'older brother' },
  { kana: 'あね',     romaji: 'ane',       meaning: 'older sister' },
  { kana: 'かぞく',   romaji: 'kazoku',    meaning: 'family' },
  { kana: 'ともだち', romaji: 'tomodachi', meaning: 'friend' },
  { kana: 'せんせい', romaji: 'sensei',    meaning: 'teacher' },
  { kana: 'なまえ',   romaji: 'namae',     meaning: 'name' },

  // --- the body ---
  { kana: 'て',       romaji: 'te',        meaning: 'hand' },
  { kana: 'あし',     romaji: 'ashi',      meaning: 'foot, leg' },
  { kana: 'め',       romaji: 'me',        meaning: 'eye' },
  { kana: 'みみ',     romaji: 'mimi',      meaning: 'ear' },
  { kana: 'くち',     romaji: 'kuchi',     meaning: 'mouth' },
  { kana: 'あたま',   romaji: 'atama',     meaning: 'head' },
  { kana: 'こころ',   romaji: 'kokoro',    meaning: 'heart, mind' },
  { kana: 'ひざ',     romaji: 'hiza',      meaning: 'knee' },
  { kana: 'はなぢ',   romaji: 'hanaji',    meaning: 'nosebleed' },

  // --- places and things ---
  { kana: 'いえ',     romaji: 'ie',        meaning: 'house' },
  { kana: 'うち',     romaji: 'uchi',      meaning: 'home' },
  { kana: 'まち',     romaji: 'machi',     meaning: 'town' },
  { kana: 'みち',     romaji: 'michi',     meaning: 'road' },
  { kana: 'えき',     romaji: 'eki',       meaning: 'station' },
  { kana: 'にわ',     romaji: 'niwa',      meaning: 'garden' },
  { kana: 'へや',     romaji: 'heya',      meaning: 'room' },
  { kana: 'まど',     romaji: 'mado',      meaning: 'window' },
  { kana: 'いす',     romaji: 'isu',       meaning: 'chair' },
  { kana: 'つくえ',   romaji: 'tsukue',    meaning: 'desk' },
  { kana: 'ほん',     romaji: 'hon',       meaning: 'book' },
  { kana: 'かみ',     romaji: 'kami',      meaning: 'paper' },
  { kana: 'とけい',   romaji: 'tokei',     meaning: 'clock, watch' },
  { kana: 'くるま',   romaji: 'kuruma',    meaning: 'car' },
  { kana: 'ふね',     romaji: 'fune',      meaning: 'boat, ship' },
  { kana: 'ひこうき', romaji: 'hikouki',   meaning: 'aeroplane' },
  { kana: 'みせ',     romaji: 'mise',      meaning: 'shop' },
  { kana: 'おかね',   romaji: 'okane',     meaning: 'money' },
  { kana: 'かばん',   romaji: 'kaban',     meaning: 'bag' },
  { kana: 'めがね',   romaji: 'megane',    meaning: 'glasses' },
  { kana: 'ぼうし',   romaji: 'boushi',    meaning: 'hat' },
  { kana: 'てがみ',   romaji: 'tegami',    meaning: 'letter' },
  { kana: 'ちず',     romaji: 'chizu',     meaning: 'map' },
  { kana: 'えんぴつ', romaji: 'enpitsu',   meaning: 'pencil' },
  { kana: 'しんぶん', romaji: 'shinbun',   meaning: 'newspaper' },
  { kana: 'でんわ',   romaji: 'denwa',     meaning: 'telephone' },
  { kana: 'でんき',   romaji: 'denki',     meaning: 'electricity, light' },
  { kana: 'ぎんこう', romaji: 'ginkou',    meaning: 'bank' },
  { kana: 'だいがく', romaji: 'daigaku',   meaning: 'university' },
  { kana: 'でぐち',   romaji: 'deguchi',   meaning: 'exit' },
  { kana: 'たてもの', romaji: 'tatemono',  meaning: 'building' },
  { kana: 'かいだん', romaji: 'kaidan',    meaning: 'stairs' },
  { kana: 'かがみ',   romaji: 'kagami',    meaning: 'mirror' },

  // --- food ---
  { kana: 'にく',     romaji: 'niku',      meaning: 'meat' },
  { kana: 'こめ',     romaji: 'kome',      meaning: 'rice (uncooked)' },
  { kana: 'ごはん',   romaji: 'gohan',     meaning: 'cooked rice, a meal' },
  { kana: 'しお',     romaji: 'shio',      meaning: 'salt' },
  { kana: 'さとう',   romaji: 'satou',     meaning: 'sugar' },
  { kana: 'みそ',     romaji: 'miso',      meaning: 'miso' },
  { kana: 'たまご',   romaji: 'tamago',    meaning: 'egg' },
  { kana: 'りんご',   romaji: 'ringo',     meaning: 'apple' },
  { kana: 'いちご',   romaji: 'ichigo',    meaning: 'strawberry' },
  { kana: 'みかん',   romaji: 'mikan',     meaning: 'mandarin orange' },
  { kana: 'すいか',   romaji: 'suika',     meaning: 'watermelon' },
  { kana: 'ぶどう',   romaji: 'budou',     meaning: 'grapes' },
  { kana: 'やさい',   romaji: 'yasai',     meaning: 'vegetable' },
  { kana: 'くだもの', romaji: 'kudamono',  meaning: 'fruit' },
  { kana: 'たべもの', romaji: 'tabemono',  meaning: 'food' },
  { kana: 'のみもの', romaji: 'nomimono',  meaning: 'a drink' },
  { kana: 'てんぷら', romaji: 'tenpura',   meaning: 'tempura' },
  { kana: 'かんぱい', romaji: 'kanpai',    meaning: 'cheers! (a toast)' },

  // --- describing things ---
  { kana: 'あお',     romaji: 'ao',        meaning: 'blue' },
  { kana: 'あか',     romaji: 'aka',       meaning: 'red' },
  { kana: 'しろ',     romaji: 'shiro',     meaning: 'white' },
  { kana: 'くろ',     romaji: 'kuro',      meaning: 'black' },
  { kana: 'おおきい', romaji: 'ookii',     meaning: 'big' },
  { kana: 'ちいさい', romaji: 'chiisai',   meaning: 'small' },
  { kana: 'たかい',   romaji: 'takai',     meaning: 'tall, expensive' },
  { kana: 'やすい',   romaji: 'yasui',     meaning: 'cheap' },
  { kana: 'あつい',   romaji: 'atsui',     meaning: 'hot' },
  { kana: 'さむい',   romaji: 'samui',     meaning: 'cold (weather)' },
  { kana: 'おいしい', romaji: 'oishii',    meaning: 'delicious' },
  { kana: 'たのしい', romaji: 'tanoshii',  meaning: 'fun, enjoyable' },
  { kana: 'うれしい', romaji: 'ureshii',   meaning: 'happy, glad' },
  { kana: 'かわいい', romaji: 'kawaii',    meaning: 'cute' },
  { kana: 'はやい',   romaji: 'hayai',     meaning: 'fast, early' },
  { kana: 'おそい',   romaji: 'osoi',      meaning: 'slow, late' },
  { kana: 'あたらしい', romaji: 'atarashii', meaning: 'new' },
  { kana: 'ふるい',   romaji: 'furui',     meaning: 'old (things)' },
  { kana: 'ちかい',   romaji: 'chikai',    meaning: 'near' },
  { kana: 'とおい',   romaji: 'tooi',      meaning: 'far' },
  { kana: 'わるい',   romaji: 'warui',     meaning: 'bad' },
  { kana: 'きれい',   romaji: 'kirei',     meaning: 'pretty, clean' },
  { kana: 'げんき',   romaji: 'genki',     meaning: 'well, energetic' },
  { kana: 'しずか',   romaji: 'shizuka',   meaning: 'quiet' },
  { kana: 'あぶない', romaji: 'abunai',    meaning: 'dangerous' },
  { kana: 'すき',     romaji: 'suki',      meaning: 'liked, fond of' },
  { kana: 'ぺらぺら', romaji: 'perapera',  meaning: 'fluent (in a language)' },

  // --- doing things ---
  { kana: 'たべる',   romaji: 'taberu',    meaning: 'to eat' },
  { kana: 'のむ',     romaji: 'nomu',      meaning: 'to drink' },
  { kana: 'ねる',     romaji: 'neru',      meaning: 'to sleep' },
  { kana: 'みる',     romaji: 'miru',      meaning: 'to see, to watch' },
  { kana: 'きく',     romaji: 'kiku',      meaning: 'to listen, to ask' },
  { kana: 'はなす',   romaji: 'hanasu',    meaning: 'to speak' },
  { kana: 'よむ',     romaji: 'yomu',      meaning: 'to read' },
  { kana: 'かく',     romaji: 'kaku',      meaning: 'to write' },
  { kana: 'いく',     romaji: 'iku',       meaning: 'to go' },
  { kana: 'くる',     romaji: 'kuru',      meaning: 'to come' },
  { kana: 'かう',     romaji: 'kau',       meaning: 'to buy' },
  { kana: 'つくる',   romaji: 'tsukuru',   meaning: 'to make' },
  { kana: 'はしる',   romaji: 'hashiru',   meaning: 'to run' },
  { kana: 'あるく',   romaji: 'aruku',     meaning: 'to walk' },
  { kana: 'およぐ',   romaji: 'oyogu',     meaning: 'to swim' },
  { kana: 'おきる',   romaji: 'okiru',     meaning: 'to get up' },
  { kana: 'すわる',   romaji: 'suwaru',    meaning: 'to sit' },
  { kana: 'つづく',   romaji: 'tsuzuku',   meaning: 'to continue' },
  { kana: 'あそぶ',   romaji: 'asobu',     meaning: 'to play' },
  { kana: 'わかる',   romaji: 'wakaru',    meaning: 'to understand' },

  // --- katakana ---
  // Loanwords spelled with plain katakana only. The long mark ー and the katakana
  // dakuten (ガ ザ ダ バ パ) are not taught yet, which rules out コーヒー, テレビ
  // and パン - the most famous loanwords are unfortunately all spelled with them.
  { kana: 'テニス',     romaji: 'tenisu',     meaning: 'tennis' },
  { kana: 'トマト',     romaji: 'tomato',     meaning: 'tomato' },
  { kana: 'メロン',     romaji: 'meron',      meaning: 'melon' },
  { kana: 'レモン',     romaji: 'remon',      meaning: 'lemon' },
  { kana: 'ホテル',     romaji: 'hoteru',     meaning: 'hotel' },
  { kana: 'ワイン',     romaji: 'wain',       meaning: 'wine' },
  { kana: 'ミルク',     romaji: 'miruku',     meaning: 'milk' },
  { kana: 'カメラ',     romaji: 'kamera',     meaning: 'camera' },
  { kana: 'レストラン', romaji: 'resutoran',  meaning: 'restaurant' },
  { kana: 'トイレ',     romaji: 'toire',      meaning: 'toilet' },
  { kana: 'クラス',     romaji: 'kurasu',     meaning: 'class' },
  { kana: 'テスト',     romaji: 'tesuto',     meaning: 'test' },
  { kana: 'テキスト',   romaji: 'tekisuto',   meaning: 'textbook' },
  { kana: 'アニメ',     romaji: 'anime',      meaning: 'anime' },
  { kana: 'カラオケ',   romaji: 'karaoke',    meaning: 'karaoke' },
  { kana: 'マラソン',   romaji: 'marason',    meaning: 'marathon' },
  { kana: 'リモコン',   romaji: 'rimokon',    meaning: 'remote control' },
  { kana: 'アイロン',   romaji: 'airon',      meaning: 'an iron (for clothes)' },
  { kana: 'エアコン',   romaji: 'eakon',      meaning: 'air conditioner' },
  { kana: 'ナイフ',     romaji: 'naifu',      meaning: 'knife' },
  { kana: 'タオル',     romaji: 'taoru',      meaning: 'towel' },
  { kana: 'マスク',     romaji: 'masuku',     meaning: 'mask' },
  { kana: 'マイク',     romaji: 'maiku',      meaning: 'microphone' },
  { kana: 'マウス',     romaji: 'mausu',      meaning: 'mouse (computer)' },
  { kana: 'ソフト',     romaji: 'sofuto',     meaning: 'software' },
  { kana: 'リスト',     romaji: 'risuto',     meaning: 'list' },
  { kana: 'チキン',     romaji: 'chikin',     meaning: 'chicken' },
  { kana: 'ハム',       romaji: 'hamu',       meaning: 'ham' },
  { kana: 'ライス',     romaji: 'raisu',      meaning: 'rice (on a plate)' },
  { kana: 'アイス',     romaji: 'aisu',       meaning: 'ice cream' },
  { kana: 'ミント',     romaji: 'minto',      meaning: 'mint' },
  { kana: 'クリスマス', romaji: 'kurisumasu', meaning: 'Christmas' },
  { kana: 'ネクタイ',   romaji: 'nekutai',    meaning: 'necktie' },
  { kana: 'ハンカチ',   romaji: 'hankachi',   meaning: 'handkerchief' },
  { kana: 'ハンサム',   romaji: 'hansamu',    meaning: 'handsome' },
  { kana: 'テント',     romaji: 'tento',      meaning: 'tent' },
  { kana: 'ヒント',     romaji: 'hinto',      meaning: 'hint' },
  { kana: 'サイン',     romaji: 'sain',       meaning: 'a signature, a sign' },
  { kana: 'ライン',     romaji: 'rain',       meaning: 'line' },
  { kana: 'コイン',     romaji: 'koin',       meaning: 'coin' },
  { kana: 'ミス',       romaji: 'misu',       meaning: 'a mistake' },
  { kana: 'メモ',       romaji: 'memo',       meaning: 'a memo, a note' },
  { kana: 'キロ',       romaji: 'kiro',       meaning: 'kilo' },
  { kana: 'センチ',     romaji: 'senchi',     meaning: 'centimetre' },
  { kana: 'アメリカ',   romaji: 'amerika',    meaning: 'America' },
  { kana: 'イタリア',   romaji: 'itaria',     meaning: 'Italy' },
  { kana: 'フランス',   romaji: 'furansu',    meaning: 'France' },
  { kana: 'ロシア',     romaji: 'roshia',     meaning: 'Russia' },
  { kana: 'スイス',     romaji: 'suisu',      meaning: 'Switzerland' },
  { kana: 'アフリカ',   romaji: 'afurika',    meaning: 'Africa' },
  { kana: 'メキシコ',   romaji: 'mekishiko',  meaning: 'Mexico' },
  { kana: 'ハワイ',     romaji: 'hawai',      meaning: 'Hawaii' },

  // --- greetings and everyday phrases ---
  { kana: 'おはよう',     romaji: 'ohayou',       meaning: 'good morning' },
  { kana: 'こんにちは',   romaji: 'konnichiwa',   meaning: 'hello, good afternoon' },
  { kana: 'こんばんは',   romaji: 'konbanwa',     meaning: 'good evening' },
  { kana: 'おやすみ',     romaji: 'oyasumi',      meaning: 'good night' },
  { kana: 'ありがとう',   romaji: 'arigatou',     meaning: 'thank you' },
  { kana: 'さようなら',   romaji: 'sayounara',    meaning: 'goodbye' },
  { kana: 'すみません',   romaji: 'sumimasen',    meaning: 'excuse me, sorry' },
  { kana: 'ごめんなさい', romaji: 'gomennasai',   meaning: 'I am sorry' },
  { kana: 'おねがい',     romaji: 'onegai',       meaning: 'a request, please' },
  { kana: 'はい',         romaji: 'hai',          meaning: 'yes' },
  { kana: 'いいえ',       romaji: 'iie',          meaning: 'no' },
  { kana: 'いただきます', romaji: 'itadakimasu',  meaning: 'said before eating' },
  { kana: 'ごちそうさま', romaji: 'gochisousama', meaning: 'said after eating' },

  // --- question words ---
  { kana: 'なに',   romaji: 'nani',  meaning: 'what' },
  { kana: 'だれ',   romaji: 'dare',  meaning: 'who' },
  { kana: 'どこ',   romaji: 'doko',  meaning: 'where' },
  { kana: 'いつ',   romaji: 'itsu',  meaning: 'when' },
  { kana: 'なぜ',   romaji: 'naze',  meaning: 'why' },
  { kana: 'どう',   romaji: 'dou',   meaning: 'how' },
  { kana: 'いくら', romaji: 'ikura', meaning: 'how much' },

  // --- numbers ---
  { kana: 'いち', romaji: 'ichi', meaning: 'one' },
  { kana: 'に',   romaji: 'ni',   meaning: 'two' },
  { kana: 'さん', romaji: 'san',  meaning: 'three' },
  { kana: 'よん', romaji: 'yon',  meaning: 'four' },
  { kana: 'ご',   romaji: 'go',   meaning: 'five' },
  { kana: 'ろく', romaji: 'roku', meaning: 'six' },
  { kana: 'なな', romaji: 'nana', meaning: 'seven' },
  { kana: 'はち', romaji: 'hachi', meaning: 'eight' },
  { kana: 'とお', romaji: 'too',  meaning: 'ten' },
  { kana: 'せん', romaji: 'sen',  meaning: 'a thousand' },
  { kana: 'まん', romaji: 'man',  meaning: 'ten thousand' },

  // --- where and when ---
  { kana: 'ここ',     romaji: 'koko',    meaning: 'here' },
  { kana: 'そこ',     romaji: 'soko',    meaning: 'there' },
  { kana: 'あそこ',   romaji: 'asoko',   meaning: 'over there' },
  { kana: 'まえ',     romaji: 'mae',     meaning: 'front, before' },
  { kana: 'うしろ',   romaji: 'ushiro',  meaning: 'behind' },
  { kana: 'となり',   romaji: 'tonari',  meaning: 'next to' },
  { kana: 'なか',     romaji: 'naka',    meaning: 'inside' },
  { kana: 'そと',     romaji: 'soto',    meaning: 'outside' },
  { kana: 'うえ',     romaji: 'ue',      meaning: 'above, on top' },
  { kana: 'した',     romaji: 'shita',   meaning: 'below, under' },
  { kana: 'いま',     romaji: 'ima',     meaning: 'now' },
  { kana: 'あとで',   romaji: 'atode',   meaning: 'later' },
  { kana: 'まいあさ', romaji: 'maiasa',  meaning: 'every morning' },
  { kana: 'まいばん', romaji: 'maiban',  meaning: 'every night' },

  // --- more describing words ---
  { kana: 'ながい',     romaji: 'nagai',      meaning: 'long' },
  { kana: 'みじかい',   romaji: 'mijikai',    meaning: 'short' },
  { kana: 'おもい',     romaji: 'omoi',       meaning: 'heavy' },
  { kana: 'かるい',     romaji: 'karui',      meaning: 'light (in weight)' },
  { kana: 'つよい',     romaji: 'tsuyoi',     meaning: 'strong' },
  { kana: 'よわい',     romaji: 'yowai',      meaning: 'weak' },
  { kana: 'あかるい',   romaji: 'akarui',     meaning: 'bright' },
  { kana: 'くらい',     romaji: 'kurai',      meaning: 'dark' },
  { kana: 'ひろい',     romaji: 'hiroi',      meaning: 'spacious' },
  { kana: 'せまい',     romaji: 'semai',      meaning: 'cramped, narrow' },
  { kana: 'つめたい',   romaji: 'tsumetai',   meaning: 'cold to the touch' },
  { kana: 'あたたかい', romaji: 'atatakai',   meaning: 'warm' },
  { kana: 'むずかしい', romaji: 'muzukashii', meaning: 'difficult' },
  { kana: 'やさしい',   romaji: 'yasashii',   meaning: 'easy, kind' },
  { kana: 'いそがしい', romaji: 'isogashii',  meaning: 'busy' },
  { kana: 'ねむい',     romaji: 'nemui',      meaning: 'sleepy' },
  { kana: 'いたい',     romaji: 'itai',       meaning: 'painful, it hurts' },
  { kana: 'こわい',     romaji: 'kowai',      meaning: 'scary' },
  { kana: 'しあわせ',   romaji: 'shiawase',   meaning: 'happiness' },

  // --- more verbs ---
  { kana: 'まつ',       romaji: 'matsu',      meaning: 'to wait' },
  { kana: 'もつ',       romaji: 'motsu',      meaning: 'to hold, to carry' },
  { kana: 'とる',       romaji: 'toru',       meaning: 'to take' },
  { kana: 'おく',       romaji: 'oku',        meaning: 'to put' },
  { kana: 'あける',     romaji: 'akeru',      meaning: 'to open' },
  { kana: 'しめる',     romaji: 'shimeru',    meaning: 'to close' },
  { kana: 'のる',       romaji: 'noru',       meaning: 'to get on, to ride' },
  { kana: 'おりる',     romaji: 'oriru',      meaning: 'to get off' },
  { kana: 'とまる',     romaji: 'tomaru',     meaning: 'to stop' },
  { kana: 'おわる',     romaji: 'owaru',      meaning: 'to finish' },
  { kana: 'ならう',     romaji: 'narau',      meaning: 'to learn' },
  { kana: 'おしえる',   romaji: 'oshieru',    meaning: 'to teach, to tell' },
  { kana: 'おぼえる',   romaji: 'oboeru',     meaning: 'to remember, to learn' },
  { kana: 'わすれる',   romaji: 'wasureru',   meaning: 'to forget' },
  { kana: 'みつける',   romaji: 'mitsukeru',  meaning: 'to find' },
  { kana: 'てつだう',   romaji: 'tetsudau',   meaning: 'to help' },
  { kana: 'あう',       romaji: 'au',         meaning: 'to meet' },
  { kana: 'かえる',     romaji: 'kaeru',      meaning: 'to go home' },
  { kana: 'つかう',     romaji: 'tsukau',     meaning: 'to use' },
  { kana: 'あらう',     romaji: 'arau',       meaning: 'to wash' },
  { kana: 'はたらく',   romaji: 'hataraku',   meaning: 'to work' },
  { kana: 'やすむ',     romaji: 'yasumu',     meaning: 'to rest' },

  // --- more places and things ---
  { kana: 'こうえん',   romaji: 'kouen',      meaning: 'park' },
  { kana: 'くうこう',   romaji: 'kuukou',     meaning: 'airport' },
  { kana: 'だいどころ', romaji: 'daidokoro',  meaning: 'kitchen' },
  { kana: 'おふろ',     romaji: 'ofuro',      meaning: 'bath' },
  { kana: 'もん',       romaji: 'mon',        meaning: 'gate' },
  { kana: 'かぎ',       romaji: 'kagi',       meaning: 'key' },
  { kana: 'さいふ',     romaji: 'saifu',      meaning: 'wallet' },
  { kana: 'くつ',       romaji: 'kutsu',      meaning: 'shoes' },
  { kana: 'ふく',       romaji: 'fuku',       meaning: 'clothes' },
  { kana: 'かさ',       romaji: 'kasa',       meaning: 'umbrella' },

  // --- more food ---
  { kana: 'たまねぎ',   romaji: 'tamanegi',   meaning: 'onion' },
  { kana: 'にんじん',   romaji: 'ninjin',     meaning: 'carrot' },
  { kana: 'とうふ',     romaji: 'toufu',      meaning: 'tofu' },
  { kana: 'あさごはん', romaji: 'asagohan',   meaning: 'breakfast' },
  { kana: 'ひるごはん', romaji: 'hirugohan',  meaning: 'lunch' },
  { kana: 'ばんごはん', romaji: 'bangohan',   meaning: 'dinner' },

  // --- more katakana ---
  { kana: 'スマホ',     romaji: 'sumaho',     meaning: 'smartphone' },
  { kana: 'サイト',     romaji: 'saito',      meaning: 'website' },
  { kana: 'ランチ',     romaji: 'ranchi',     meaning: 'lunch' },
  { kana: 'ライト',     romaji: 'raito',      meaning: 'light, lamp' },
  { kana: 'ハサミ',     romaji: 'hasami',     meaning: 'scissors' },
  { kana: 'インク',     romaji: 'inku',       meaning: 'ink' },
  { kana: 'コンセント', romaji: 'konsento',   meaning: 'power socket' },
  { kana: 'ワクチン',   romaji: 'wakuchin',   meaning: 'vaccine' },
  { kana: 'スタイル',   romaji: 'sutairu',    meaning: 'style' },
  { kana: 'ホチキス',   romaji: 'hochikisu',  meaning: 'stapler' },
  { kana: 'カクテル',   romaji: 'kakuteru',   meaning: 'cocktail' },
  { kana: 'リサイクル', romaji: 'risaikuru',  meaning: 'recycling' },

  // --- more animals ---
  { kana: 'かめ',       romaji: 'kame',       meaning: 'turtle' },
  { kana: 'かに',       romaji: 'kani',       meaning: 'crab' },
  { kana: 'いか',       romaji: 'ika',        meaning: 'squid' },
  { kana: 'たこ',       romaji: 'tako',       meaning: 'octopus' },
  { kana: 'くま',       romaji: 'kuma',       meaning: 'bear' },
  { kana: 'さる',       romaji: 'saru',       meaning: 'monkey' },
  { kana: 'しか',       romaji: 'shika',      meaning: 'deer' },
  { kana: 'にわとり',   romaji: 'niwatori',   meaning: 'chicken' },
  { kana: 'からす',     romaji: 'karasu',     meaning: 'crow' },
  { kana: 'はと',       romaji: 'hato',       meaning: 'pigeon' },
  { kana: 'むし',       romaji: 'mushi',      meaning: 'insect' },
  { kana: 'あり',       romaji: 'ari',        meaning: 'ant' },
  { kana: 'ねずみ',     romaji: 'nezumi',     meaning: 'mouse, rat' },
  { kana: 'とんぼ',     romaji: 'tonbo',      meaning: 'dragonfly' },
  { kana: 'えび',       romaji: 'ebi',        meaning: 'prawn, shrimp' },
  { kana: 'ひつじ',     romaji: 'hitsuji',    meaning: 'sheep' },
  { kana: 'すずめ',     romaji: 'suzume',     meaning: 'sparrow' },

  // --- more of the natural world ---
  { kana: 'たね',       romaji: 'tane',       meaning: 'seed' },
  { kana: 'もり',       romaji: 'mori',       meaning: 'forest' },
  { kana: 'はやし',     romaji: 'hayashi',    meaning: 'woods' },
  { kana: 'はたけ',     romaji: 'hatake',     meaning: 'field, farm plot' },
  { kana: 'いし',       romaji: 'ishi',       meaning: 'stone' },
  { kana: 'すな',       romaji: 'suna',       meaning: 'sand' },
  { kana: 'つち',       romaji: 'tsuchi',     meaning: 'soil, earth' },
  { kana: 'ほのお',     romaji: 'honoo',      meaning: 'flame' },
  { kana: 'けむり',     romaji: 'kemuri',     meaning: 'smoke' },
  { kana: 'こおり',     romaji: 'koori',      meaning: 'ice' },
  { kana: 'たき',       romaji: 'taki',       meaning: 'waterfall' },
  { kana: 'おか',       romaji: 'oka',        meaning: 'hill' },
  { kana: 'たに',       romaji: 'tani',       meaning: 'valley' },
  { kana: 'しま',       romaji: 'shima',      meaning: 'island' },
  { kana: 'みなと',     romaji: 'minato',     meaning: 'harbour' },
  { kana: 'みずうみ',   romaji: 'mizuumi',    meaning: 'lake' },
  { kana: 'いずみ',     romaji: 'izumi',      meaning: 'spring, fountain' },

  // --- more of the body ---
  { kana: 'かお',       romaji: 'kao',        meaning: 'face' },
  { kana: 'かた',       romaji: 'kata',       meaning: 'shoulder' },
  { kana: 'せなか',     romaji: 'senaka',     meaning: 'back' },
  { kana: 'おなか',     romaji: 'onaka',      meaning: 'stomach, belly' },
  { kana: 'つめ',       romaji: 'tsume',      meaning: 'fingernail' },
  { kana: 'かみのけ',   romaji: 'kaminoke',   meaning: 'hair' },
  { kana: 'こし',       romaji: 'koshi',      meaning: 'lower back, hips' },
  { kana: 'ほね',       romaji: 'hone',       meaning: 'bone' },
  { kana: 'ち',         romaji: 'chi',        meaning: 'blood' },
  { kana: 'あせ',       romaji: 'ase',        meaning: 'sweat' },
  { kana: 'いき',       romaji: 'iki',        meaning: 'breath' },
  { kana: 'くび',       romaji: 'kubi',       meaning: 'neck' },
  { kana: 'ゆび',       romaji: 'yubi',       meaning: 'finger' },
  { kana: 'ひげ',       romaji: 'hige',       meaning: 'beard, moustache' },
  { kana: 'なみだ',     romaji: 'namida',     meaning: 'tears' },
  { kana: 'くすり',     romaji: 'kusuri',     meaning: 'medicine' },
  { kana: 'ねつ',       romaji: 'netsu',      meaning: 'a fever' },
  { kana: 'けが',       romaji: 'kega',       meaning: 'an injury' },

  // --- more around the house ---
  { kana: 'さら',       romaji: 'sara',       meaning: 'plate' },
  { kana: 'はし',       romaji: 'hashi',      meaning: 'chopsticks, bridge' },
  { kana: 'ふとん',     romaji: 'futon',      meaning: 'futon, bedding' },
  { kana: 'まくら',     romaji: 'makura',     meaning: 'pillow' },
  { kana: 'たな',       romaji: 'tana',       meaning: 'shelf' },
  { kana: 'ゆか',       romaji: 'yuka',       meaning: 'floor' },
  { kana: 'はしら',     romaji: 'hashira',    meaning: 'pillar, post' },
  { kana: 'やね',       romaji: 'yane',       meaning: 'roof' },
  { kana: 'ほうき',     romaji: 'houki',      meaning: 'broom' },
  { kana: 'くし',       romaji: 'kushi',      meaning: 'comb' },
  { kana: 'かみそり',   romaji: 'kamisori',   meaning: 'razor' },
  { kana: 'いと',       romaji: 'ito',        meaning: 'thread' },
  { kana: 'はり',       romaji: 'hari',       meaning: 'needle' },
  { kana: 'ぬの',       romaji: 'nuno',       meaning: 'cloth' },
  { kana: 'なべ',       romaji: 'nabe',       meaning: 'pot, hotpot' },
  { kana: 'かべ',       romaji: 'kabe',       meaning: 'wall' },
  { kana: 'ひきだし',   romaji: 'hikidashi',  meaning: 'drawer' },

  // --- more people ---
  { kana: 'むすこ',     romaji: 'musuko',     meaning: 'son' },
  { kana: 'むすめ',     romaji: 'musume',     meaning: 'daughter' },
  { kana: 'つま',       romaji: 'tsuma',      meaning: 'wife' },
  { kana: 'なかま',     romaji: 'nakama',     meaning: 'companion, mate' },
  { kana: 'せいと',     romaji: 'seito',      meaning: 'pupil' },
  { kana: 'けいさつ',   romaji: 'keisatsu',   meaning: 'police' },
  { kana: 'てんいん',   romaji: "ten'in",     meaning: 'shop assistant' },
  { kana: 'おじさん',   romaji: 'ojisan',     meaning: 'uncle, middle-aged man' },
  { kana: 'おばさん',   romaji: 'obasan',     meaning: 'aunt, middle-aged woman' },
  { kana: 'おじいさん', romaji: 'ojiisan',    meaning: 'grandfather, old man' },
  { kana: 'おばあさん', romaji: 'obaasan',    meaning: 'grandmother, old woman' },
  { kana: 'がくせい',   romaji: 'gakusei',    meaning: 'student' },

  // --- more places ---
  { kana: 'むら',       romaji: 'mura',       meaning: 'village' },
  { kana: 'くに',       romaji: 'kuni',       meaning: 'country' },
  { kana: 'せかい',     romaji: 'sekai',      meaning: 'the world' },
  { kana: 'こうさてん', romaji: 'kousaten',   meaning: 'intersection' },
  { kana: 'くすりや',   romaji: 'kusuriya',   meaning: 'pharmacy' },
  { kana: 'ほんや',     romaji: 'honya',      meaning: 'bookshop' },
  { kana: 'はなや',     romaji: 'hanaya',     meaning: 'florist' },
  { kana: 'にくや',     romaji: 'nikuya',     meaning: 'butcher' },
  { kana: 'さかなや',   romaji: 'sakanaya',   meaning: 'fishmonger' },
  { kana: 'やおや',     romaji: 'yaoya',      meaning: 'greengrocer' },
  { kana: 'いちば',     romaji: 'ichiba',     meaning: 'market' },
  { kana: 'こうばん',   romaji: 'kouban',     meaning: 'police box' },
  { kana: 'しんごう',   romaji: 'shingou',    meaning: 'traffic light' },
  { kana: 'ほどう',     romaji: 'hodou',      meaning: 'pavement, footpath' },
  { kana: 'うみべ',     romaji: 'umibe',      meaning: 'seaside' },

  // --- more doing words ---
  { kana: 'のぼる',     romaji: 'noboru',     meaning: 'to climb' },
  { kana: 'おちる',     romaji: 'ochiru',     meaning: 'to fall' },
  { kana: 'うける',     romaji: 'ukeru',      meaning: 'to receive, to take (a test)' },
  { kana: 'きめる',     romaji: 'kimeru',     meaning: 'to decide' },
  { kana: 'きまる',     romaji: 'kimaru',     meaning: 'to be decided' },
  { kana: 'いのる',     romaji: 'inoru',      meaning: 'to pray' },
  { kana: 'わらう',     romaji: 'warau',      meaning: 'to laugh' },
  { kana: 'なく',       romaji: 'naku',       meaning: 'to cry' },
  { kana: 'おこる',     romaji: 'okoru',      meaning: 'to get angry' },
  { kana: 'かなしむ',   romaji: 'kanashimu',  meaning: 'to feel sad' },
  { kana: 'つかれる',   romaji: 'tsukareru',  meaning: 'to get tired' },
  { kana: 'なおる',     romaji: 'naoru',      meaning: 'to get better' },
  { kana: 'なおす',     romaji: 'naosu',      meaning: 'to fix' },
  { kana: 'こまる',     romaji: 'komaru',     meaning: 'to be troubled' },
  { kana: 'かつ',       romaji: 'katsu',      meaning: 'to win' },
  { kana: 'すてる',     romaji: 'suteru',     meaning: 'to throw away' },
  { kana: 'ひろう',     romaji: 'hirou',      meaning: 'to pick up' },
  { kana: 'きえる',     romaji: 'kieru',      meaning: 'to disappear' },
  { kana: 'ひかる',     romaji: 'hikaru',     meaning: 'to shine' },
  { kana: 'もえる',     romaji: 'moeru',      meaning: 'to burn' },
  { kana: 'こわれる',   romaji: 'kowareru',   meaning: 'to break' },
  { kana: 'うる',       romaji: 'uru',        meaning: 'to sell' },
  { kana: 'かす',       romaji: 'kasu',       meaning: 'to lend' },
  { kana: 'かりる',     romaji: 'kariru',     meaning: 'to borrow' },
  { kana: 'はらう',     romaji: 'harau',      meaning: 'to pay' },
  { kana: 'おくる',     romaji: 'okuru',      meaning: 'to send' },
  { kana: 'もらう',     romaji: 'morau',      meaning: 'to receive' },
  { kana: 'しる',       romaji: 'shiru',      meaning: 'to know' },
  { kana: 'いう',       romaji: 'iu',         meaning: 'to say' },
  { kana: 'なげる',     romaji: 'nageru',     meaning: 'to throw' },
  { kana: 'くばる',     romaji: 'kubaru',     meaning: 'to hand out' },
  { kana: 'かんがえる', romaji: 'kangaeru',   meaning: 'to think' },
  { kana: 'しんじる',   romaji: 'shinjiru',   meaning: 'to believe' },
  { kana: 'ねがう',     romaji: 'negau',      meaning: 'to wish' },
  { kana: 'おどろく',   romaji: 'odoroku',    meaning: 'to be surprised' },
  { kana: 'よろこぶ',   romaji: 'yorokobu',   meaning: 'to be delighted' },
  { kana: 'まける',     romaji: 'makeru',     meaning: 'to lose' },
  { kana: 'はこぶ',     romaji: 'hakobu',     meaning: 'to carry' },
  { kana: 'ならべる',   romaji: 'naraberu',   meaning: 'to line up' },
  { kana: 'かたづける', romaji: 'katazukeru', meaning: 'to tidy up' },
  { kana: 'とどく',     romaji: 'todoku',     meaning: 'to arrive, to be delivered' },
  { kana: 'あげる',     romaji: 'ageru',      meaning: 'to give' },
  { kana: 'できる',     romaji: 'dekiru',     meaning: 'to be able to' },

  // --- more describing words ---
  { kana: 'あまい',     romaji: 'amai',       meaning: 'sweet' },
  { kana: 'からい',     romaji: 'karai',      meaning: 'spicy' },
  { kana: 'うすい',     romaji: 'usui',       meaning: 'thin, weak' },
  { kana: 'ふとい',     romaji: 'futoi',      meaning: 'thick, fat' },
  { kana: 'ほそい',     romaji: 'hosoi',      meaning: 'slender' },
  { kana: 'まるい',     romaji: 'marui',      meaning: 'round' },
  { kana: 'しかくい',   romaji: 'shikakui',   meaning: 'square' },
  { kana: 'きたない',   romaji: 'kitanai',    meaning: 'dirty' },
  { kana: 'うつくしい', romaji: 'utsukushii', meaning: 'beautiful' },
  { kana: 'うるさい',   romaji: 'urusai',     meaning: 'noisy' },
  { kana: 'ほんとう',   romaji: 'hontou',     meaning: 'true, real' },
  { kana: 'うそ',       romaji: 'uso',        meaning: 'a lie' },
  { kana: 'たいせつ',   romaji: 'taisetsu',   meaning: 'important' },
  { kana: 'ひつよう',   romaji: 'hitsuyou',   meaning: 'necessary' },
  { kana: 'へた',       romaji: 'heta',       meaning: 'bad at something' },
  { kana: 'にがい',     romaji: 'nigai',      meaning: 'bitter' },
  { kana: 'すばらしい', romaji: 'subarashii', meaning: 'wonderful' },
  { kana: 'めずらしい', romaji: 'mezurashii', meaning: 'rare, unusual' },
  { kana: 'ただしい',   romaji: 'tadashii',   meaning: 'correct' },
  { kana: 'まちがい',   romaji: 'machigai',   meaning: 'a mistake' },

  // --- more time and amount ---
  { kana: 'おととい',   romaji: 'ototoi',     meaning: 'the day before yesterday' },
  { kana: 'らいねん',   romaji: 'rainen',     meaning: 'next year' },
  { kana: 'ひるま',     romaji: 'hiruma',     meaning: 'daytime' },
  { kana: 'よなか',     romaji: 'yonaka',     meaning: 'the middle of the night' },
  { kana: 'とき',       romaji: 'toki',       meaning: 'time, when' },
  { kana: 'おわり',     romaji: 'owari',      meaning: 'the end' },
  { kana: 'いつも',     romaji: 'itsumo',     meaning: 'always' },
  { kana: 'もう',       romaji: 'mou',        meaning: 'already' },
  { kana: 'また',       romaji: 'mata',       meaning: 'again' },
  { kana: 'すこし',     romaji: 'sukoshi',    meaning: 'a little' },
  { kana: 'たくさん',   romaji: 'takusan',    meaning: 'a lot' },
  { kana: 'みんな',     romaji: 'minna',      meaning: 'everyone' },
  { kana: 'ひとり',     romaji: 'hitori',     meaning: 'one person, alone' },
  { kana: 'ふたり',     romaji: 'futari',     meaning: 'two people' },
  { kana: 'ゆうがた',   romaji: 'yuugata',    meaning: 'evening' },
  { kana: 'あいだ',     romaji: 'aida',       meaning: 'between' },
  { kana: 'はじめ',     romaji: 'hajime',     meaning: 'the beginning' },
  { kana: 'つぎ',       romaji: 'tsugi',      meaning: 'next' },
  { kana: 'さいご',     romaji: 'saigo',      meaning: 'the last' },
  { kana: 'ときどき',   romaji: 'tokidoki',   meaning: 'sometimes' },
  { kana: 'すぐ',       romaji: 'sugu',       meaning: 'right away' },
  { kana: 'まだ',       romaji: 'mada',       meaning: 'not yet, still' },
  { kana: 'ぜんぶ',     romaji: 'zenbu',      meaning: 'all of it' },
  { kana: 'はんぶん',   romaji: 'hanbun',     meaning: 'half' },

  // --- more katakana ---
  { kana: 'ウイルス',   romaji: 'uirusu',     meaning: 'virus' },
  { kana: 'メトロ',     romaji: 'metoro',     meaning: 'metro' },
  { kana: 'トンネル',   romaji: 'tonneru',    meaning: 'tunnel' },
  { kana: 'タイヤ',     romaji: 'taiya',      meaning: 'tyre' },
  { kana: 'オイル',     romaji: 'oiru',       meaning: 'oil' },
  { kana: 'ナイロン',   romaji: 'nairon',     meaning: 'nylon' },
  { kana: 'シルク',     romaji: 'shiruku',    meaning: 'silk' },
  { kana: 'リネン',     romaji: 'rinen',      meaning: 'linen' },
  { kana: 'ホワイト',   romaji: 'howaito',    meaning: 'white' },
  { kana: 'メイク',     romaji: 'meiku',      meaning: 'make-up' },
  { kana: 'リンス',     romaji: 'rinsu',      meaning: 'hair conditioner' },
  { kana: 'アカウント', romaji: 'akaunto',    meaning: 'account' },
  { kana: 'コメント',   romaji: 'komento',    meaning: 'comment' },
  { kana: 'スキル',     romaji: 'sukiru',     meaning: 'skill' },
  { kana: 'リスク',     romaji: 'risuku',     meaning: 'risk' },
  { kana: 'コスト',     romaji: 'kosuto',     meaning: 'cost' },
  { kana: 'ソロ',       romaji: 'soro',       meaning: 'solo' },
  { kana: 'フロント',   romaji: 'furonto',    meaning: 'hotel front desk' },
  { kana: 'テラス',     romaji: 'terasu',     meaning: 'terrace' },
  { kana: 'ツナ',       romaji: 'tsuna',      meaning: 'tuna' },
  { kana: 'レタス',     romaji: 'retasu',     meaning: 'lettuce' },
  { kana: 'ニンニク',   romaji: 'ninniku',    meaning: 'garlic' },
  { kana: 'セロリ',     romaji: 'serori',     meaning: 'celery' },
  { kana: 'タイ',       romaji: 'tai',        meaning: 'Thailand' },
  { kana: 'トルコ',     romaji: 'toruko',     meaning: 'Turkey' },
  { kana: 'イラン',     romaji: 'iran',       meaning: 'Iran' },
  { kana: 'イラク',     romaji: 'iraku',      meaning: 'Iraq' },
  { kana: 'チリ',       romaji: 'chiri',      meaning: 'Chile' },
  { kana: 'ケニア',     romaji: 'kenia',      meaning: 'Kenya' },
  { kana: 'シアトル',   romaji: 'shiatoru',   meaning: 'Seattle' },
  { kana: 'ソウル',     romaji: 'souru',      meaning: 'Seoul' },
  { kana: 'マニラ',     romaji: 'manira',     meaning: 'Manila' },
  { kana: 'カイロ',     romaji: 'kairo',      meaning: 'Cairo' },
  { kana: 'アテネ',     romaji: 'atene',      meaning: 'Athens' },
  { kana: 'テクノ',     romaji: 'tekuno',     meaning: 'techno (music)' },
  { kana: 'ヘア',       romaji: 'hea',        meaning: 'hair' },
  { kana: 'ユネスコ',   romaji: 'yunesuko',   meaning: 'UNESCO' }
];
