// Words for reading practice, written in kana only.
//
// Every word here is spelled using nothing but the 46 basic hiragana and the 25
// dakuten characters, so you never meet a character the app has not taught you.
// That rules out anything needing the small っ or ゃ ゅ ょ - so no がっこう and no
// でんしゃ - until those are added as their own set.
//
// Which set a word belongs to is worked out in code from its characters, not
// tagged by hand, so it cannot drift out of step. A word is offered in a set only
// when every one of its characters is taught by that set.

var WORDS = [
  // --- animals and nature ---
  { kana: 'ねこ',     romaji: 'neko',      meaning: 'cat' },
  { kana: 'いぬ',     romaji: 'inu',       meaning: 'dog' },
  { kana: 'とり',     romaji: 'tori',      meaning: 'bird' },
  { kana: 'さかな',   romaji: 'sakana',    meaning: 'fish' },
  { kana: 'うま',     romaji: 'uma',       meaning: 'horse' },
  { kana: 'うし',     romaji: 'ushi',      meaning: 'cow' },
  { kana: 'ぶた',     romaji: 'buta',      meaning: 'pig' },
  { kana: 'うさぎ',   romaji: 'usagi',     meaning: 'rabbit' },
  { kana: 'とかげ',   romaji: 'tokage',    meaning: 'lizard' },
  { kana: 'どうぶつ', romaji: 'doubutsu',  meaning: 'animal' },
  { kana: 'やま',     romaji: 'yama',      meaning: 'mountain' },
  { kana: 'かわ',     romaji: 'kawa',      meaning: 'river' },
  { kana: 'うみ',     romaji: 'umi',       meaning: 'sea' },
  { kana: 'そら',     romaji: 'sora',      meaning: 'sky' },
  { kana: 'ほし',     romaji: 'hoshi',     meaning: 'star' },
  { kana: 'つき',     romaji: 'tsuki',     meaning: 'moon' },
  { kana: 'はな',     romaji: 'hana',      meaning: 'flower' },
  { kana: 'くさ',     romaji: 'kusa',      meaning: 'grass' },
  { kana: 'き',       romaji: 'ki',        meaning: 'tree' },
  { kana: 'みず',     romaji: 'mizu',      meaning: 'water' },
  { kana: 'あめ',     romaji: 'ame',       meaning: 'rain' },
  { kana: 'ゆき',     romaji: 'yuki',      meaning: 'snow' },
  { kana: 'かぜ',     romaji: 'kaze',      meaning: 'wind' },
  { kana: 'ひまわり', romaji: 'himawari',  meaning: 'sunflower' },
  { kana: 'はなび',   romaji: 'hanabi',    meaning: 'fireworks' },
  { kana: 'にじ',     romaji: 'niji',      meaning: 'rainbow' },

  // --- time ---
  { kana: 'はる',     romaji: 'haru',      meaning: 'spring' },
  { kana: 'なつ',     romaji: 'natsu',     meaning: 'summer' },
  { kana: 'あき',     romaji: 'aki',       meaning: 'autumn' },
  { kana: 'ふゆ',     romaji: 'fuyu',      meaning: 'winter' },
  { kana: 'あさ',     romaji: 'asa',       meaning: 'morning' },
  { kana: 'ひる',     romaji: 'hiru',      meaning: 'daytime, noon' },
  { kana: 'よる',     romaji: 'yoru',      meaning: 'night' },
  { kana: 'きのう',   romaji: 'kinou',     meaning: 'yesterday' },
  { kana: 'あした',   romaji: 'ashita',    meaning: 'tomorrow' },
  { kana: 'ことし',   romaji: 'kotoshi',   meaning: 'this year' },
  { kana: 'まいにち', romaji: 'mainichi',  meaning: 'every day' },
  { kana: 'じかん',   romaji: 'jikan',     meaning: 'time, an hour' },
  { kana: 'さんぽ',   romaji: 'sanpo',     meaning: 'a walk, a stroll' },

  // --- people ---
  { kana: 'ひと',     romaji: 'hito',      meaning: 'person' },
  { kana: 'おとこ',   romaji: 'otoko',     meaning: 'man' },
  { kana: 'おんな',   romaji: 'onna',      meaning: 'woman' },
  { kana: 'こども',   romaji: 'kodomo',    meaning: 'child' },
  { kana: 'ちち',     romaji: 'chichi',    meaning: 'father' },
  { kana: 'はは',     romaji: 'haha',      meaning: 'mother' },
  { kana: 'あに',     romaji: 'ani',       meaning: 'older brother' },
  { kana: 'あね',     romaji: 'ane',       meaning: 'older sister' },
  { kana: 'かぞく',   romaji: 'kazoku',    meaning: 'family' },
  { kana: 'ともだち', romaji: 'tomodachi', meaning: 'friend' },
  { kana: 'せんせい', romaji: 'sensei',    meaning: 'teacher' },
  { kana: 'なまえ',   romaji: 'namae',     meaning: 'name' },

  // --- the body ---
  { kana: 'て',       romaji: 'te',        meaning: 'hand' },
  { kana: 'あし',     romaji: 'ashi',      meaning: 'foot, leg' },
  { kana: 'め',       romaji: 'me',        meaning: 'eye' },
  { kana: 'みみ',     romaji: 'mimi',      meaning: 'ear' },
  { kana: 'くち',     romaji: 'kuchi',     meaning: 'mouth' },
  { kana: 'あたま',   romaji: 'atama',     meaning: 'head' },
  { kana: 'こころ',   romaji: 'kokoro',    meaning: 'heart, mind' },
  { kana: 'ひざ',     romaji: 'hiza',      meaning: 'knee' },
  { kana: 'はなぢ',   romaji: 'hanaji',    meaning: 'nosebleed' },

  // --- places and things ---
  { kana: 'いえ',     romaji: 'ie',        meaning: 'house' },
  { kana: 'うち',     romaji: 'uchi',      meaning: 'home' },
  { kana: 'まち',     romaji: 'machi',     meaning: 'town' },
  { kana: 'みち',     romaji: 'michi',     meaning: 'road' },
  { kana: 'えき',     romaji: 'eki',       meaning: 'station' },
  { kana: 'にわ',     romaji: 'niwa',      meaning: 'garden' },
  { kana: 'へや',     romaji: 'heya',      meaning: 'room' },
  { kana: 'まど',     romaji: 'mado',      meaning: 'window' },
  { kana: 'いす',     romaji: 'isu',       meaning: 'chair' },
  { kana: 'つくえ',   romaji: 'tsukue',    meaning: 'desk' },
  { kana: 'ほん',     romaji: 'hon',       meaning: 'book' },
  { kana: 'かみ',     romaji: 'kami',      meaning: 'paper' },
  { kana: 'とけい',   romaji: 'tokei',     meaning: 'clock, watch' },
  { kana: 'くるま',   romaji: 'kuruma',    meaning: 'car' },
  { kana: 'ふね',     romaji: 'fune',      meaning: 'boat, ship' },
  { kana: 'ひこうき', romaji: 'hikouki',   meaning: 'aeroplane' },
  { kana: 'みせ',     romaji: 'mise',      meaning: 'shop' },
  { kana: 'おかね',   romaji: 'okane',     meaning: 'money' },
  { kana: 'かばん',   romaji: 'kaban',     meaning: 'bag' },
  { kana: 'めがね',   romaji: 'megane',    meaning: 'glasses' },
  { kana: 'ぼうし',   romaji: 'boushi',    meaning: 'hat' },
  { kana: 'てがみ',   romaji: 'tegami',    meaning: 'letter' },
  { kana: 'ちず',     romaji: 'chizu',     meaning: 'map' },
  { kana: 'えんぴつ', romaji: 'enpitsu',   meaning: 'pencil' },
  { kana: 'しんぶん', romaji: 'shinbun',   meaning: 'newspaper' },
  { kana: 'でんわ',   romaji: 'denwa',     meaning: 'telephone' },
  { kana: 'でんき',   romaji: 'denki',     meaning: 'electricity, light' },
  { kana: 'ぎんこう', romaji: 'ginkou',    meaning: 'bank' },
  { kana: 'だいがく', romaji: 'daigaku',   meaning: 'university' },
  { kana: 'でぐち',   romaji: 'deguchi',   meaning: 'exit' },
  { kana: 'たてもの', romaji: 'tatemono',  meaning: 'building' },
  { kana: 'かいだん', romaji: 'kaidan',    meaning: 'stairs' },
  { kana: 'かがみ',   romaji: 'kagami',    meaning: 'mirror' },

  // --- food ---
  { kana: 'にく',     romaji: 'niku',      meaning: 'meat' },
  { kana: 'こめ',     romaji: 'kome',      meaning: 'rice (uncooked)' },
  { kana: 'ごはん',   romaji: 'gohan',     meaning: 'cooked rice, a meal' },
  { kana: 'しお',     romaji: 'shio',      meaning: 'salt' },
  { kana: 'さとう',   romaji: 'satou',     meaning: 'sugar' },
  { kana: 'みそ',     romaji: 'miso',      meaning: 'miso' },
  { kana: 'たまご',   romaji: 'tamago',    meaning: 'egg' },
  { kana: 'りんご',   romaji: 'ringo',     meaning: 'apple' },
  { kana: 'いちご',   romaji: 'ichigo',    meaning: 'strawberry' },
  { kana: 'みかん',   romaji: 'mikan',     meaning: 'mandarin orange' },
  { kana: 'すいか',   romaji: 'suika',     meaning: 'watermelon' },
  { kana: 'ぶどう',   romaji: 'budou',     meaning: 'grapes' },
  { kana: 'やさい',   romaji: 'yasai',     meaning: 'vegetable' },
  { kana: 'くだもの', romaji: 'kudamono',  meaning: 'fruit' },
  { kana: 'たべもの', romaji: 'tabemono',  meaning: 'food' },
  { kana: 'のみもの', romaji: 'nomimono',  meaning: 'a drink' },
  { kana: 'てんぷら', romaji: 'tenpura',   meaning: 'tempura' },
  { kana: 'かんぱい', romaji: 'kanpai',    meaning: 'cheers! (a toast)' },

  // --- describing things ---
  { kana: 'あお',     romaji: 'ao',        meaning: 'blue' },
  { kana: 'あか',     romaji: 'aka',       meaning: 'red' },
  { kana: 'しろ',     romaji: 'shiro',     meaning: 'white' },
  { kana: 'くろ',     romaji: 'kuro',      meaning: 'black' },
  { kana: 'おおきい', romaji: 'ookii',     meaning: 'big' },
  { kana: 'ちいさい', romaji: 'chiisai',   meaning: 'small' },
  { kana: 'たかい',   romaji: 'takai',     meaning: 'tall, expensive' },
  { kana: 'やすい',   romaji: 'yasui',     meaning: 'cheap' },
  { kana: 'あつい',   romaji: 'atsui',     meaning: 'hot' },
  { kana: 'さむい',   romaji: 'samui',     meaning: 'cold (weather)' },
  { kana: 'おいしい', romaji: 'oishii',    meaning: 'delicious' },
  { kana: 'たのしい', romaji: 'tanoshii',  meaning: 'fun, enjoyable' },
  { kana: 'うれしい', romaji: 'ureshii',   meaning: 'happy, glad' },
  { kana: 'かわいい', romaji: 'kawaii',    meaning: 'cute' },
  { kana: 'はやい',   romaji: 'hayai',     meaning: 'fast, early' },
  { kana: 'おそい',   romaji: 'osoi',      meaning: 'slow, late' },
  { kana: 'あたらしい', romaji: 'atarashii', meaning: 'new' },
  { kana: 'ふるい',   romaji: 'furui',     meaning: 'old (things)' },
  { kana: 'ちかい',   romaji: 'chikai',    meaning: 'near' },
  { kana: 'とおい',   romaji: 'tooi',      meaning: 'far' },
  { kana: 'わるい',   romaji: 'warui',     meaning: 'bad' },
  { kana: 'きれい',   romaji: 'kirei',     meaning: 'pretty, clean' },
  { kana: 'げんき',   romaji: 'genki',     meaning: 'well, energetic' },
  { kana: 'しずか',   romaji: 'shizuka',   meaning: 'quiet' },
  { kana: 'あぶない', romaji: 'abunai',    meaning: 'dangerous' },
  { kana: 'すき',     romaji: 'suki',      meaning: 'liked, fond of' },
  { kana: 'ぺらぺら', romaji: 'perapera',  meaning: 'fluent (in a language)' },

  // --- doing things ---
  { kana: 'たべる',   romaji: 'taberu',    meaning: 'to eat' },
  { kana: 'のむ',     romaji: 'nomu',      meaning: 'to drink' },
  { kana: 'ねる',     romaji: 'neru',      meaning: 'to sleep' },
  { kana: 'みる',     romaji: 'miru',      meaning: 'to see, to watch' },
  { kana: 'きく',     romaji: 'kiku',      meaning: 'to listen, to ask' },
  { kana: 'はなす',   romaji: 'hanasu',    meaning: 'to speak' },
  { kana: 'よむ',     romaji: 'yomu',      meaning: 'to read' },
  { kana: 'かく',     romaji: 'kaku',      meaning: 'to write' },
  { kana: 'いく',     romaji: 'iku',       meaning: 'to go' },
  { kana: 'くる',     romaji: 'kuru',      meaning: 'to come' },
  { kana: 'かう',     romaji: 'kau',       meaning: 'to buy' },
  { kana: 'つくる',   romaji: 'tsukuru',   meaning: 'to make' },
  { kana: 'はしる',   romaji: 'hashiru',   meaning: 'to run' },
  { kana: 'あるく',   romaji: 'aruku',     meaning: 'to walk' },
  { kana: 'およぐ',   romaji: 'oyogu',     meaning: 'to swim' },
  { kana: 'おきる',   romaji: 'okiru',     meaning: 'to get up' },
  { kana: 'すわる',   romaji: 'suwaru',    meaning: 'to sit' },
  { kana: 'つづく',   romaji: 'tsuzuku',   meaning: 'to continue' },
  { kana: 'あそぶ',   romaji: 'asobu',     meaning: 'to play' },
  { kana: 'わかる',   romaji: 'wakaru',    meaning: 'to understand' },

  // --- katakana ---
  // Loanwords spelled with plain katakana only. The long mark ー and the katakana
  // dakuten (ガ ザ ダ バ パ) are not taught yet, which rules out コーヒー, テレビ
  // and パン - the most famous loanwords are unfortunately all spelled with them.
  { kana: 'テニス',     romaji: 'tenisu',     meaning: 'tennis' },
  { kana: 'トマト',     romaji: 'tomato',     meaning: 'tomato' },
  { kana: 'メロン',     romaji: 'meron',      meaning: 'melon' },
  { kana: 'レモン',     romaji: 'remon',      meaning: 'lemon' },
  { kana: 'ホテル',     romaji: 'hoteru',     meaning: 'hotel' },
  { kana: 'ワイン',     romaji: 'wain',       meaning: 'wine' },
  { kana: 'ミルク',     romaji: 'miruku',     meaning: 'milk' },
  { kana: 'カメラ',     romaji: 'kamera',     meaning: 'camera' },
  { kana: 'レストラン', romaji: 'resutoran',  meaning: 'restaurant' },
  { kana: 'トイレ',     romaji: 'toire',      meaning: 'toilet' },
  { kana: 'クラス',     romaji: 'kurasu',     meaning: 'class' },
  { kana: 'テスト',     romaji: 'tesuto',     meaning: 'test' },
  { kana: 'テキスト',   romaji: 'tekisuto',   meaning: 'textbook' },
  { kana: 'アニメ',     romaji: 'anime',      meaning: 'anime' },
  { kana: 'カラオケ',   romaji: 'karaoke',    meaning: 'karaoke' },
  { kana: 'マラソン',   romaji: 'marason',    meaning: 'marathon' },
  { kana: 'リモコン',   romaji: 'rimokon',    meaning: 'remote control' },
  { kana: 'アイロン',   romaji: 'airon',      meaning: 'an iron (for clothes)' },
  { kana: 'エアコン',   romaji: 'eakon',      meaning: 'air conditioner' },
  { kana: 'ナイフ',     romaji: 'naifu',      meaning: 'knife' },
  { kana: 'タオル',     romaji: 'taoru',      meaning: 'towel' },
  { kana: 'マスク',     romaji: 'masuku',     meaning: 'mask' },
  { kana: 'マイク',     romaji: 'maiku',      meaning: 'microphone' },
  { kana: 'マウス',     romaji: 'mausu',      meaning: 'mouse (computer)' },
  { kana: 'ソフト',     romaji: 'sofuto',     meaning: 'software' },
  { kana: 'リスト',     romaji: 'risuto',     meaning: 'list' },
  { kana: 'チキン',     romaji: 'chikin',     meaning: 'chicken' },
  { kana: 'ハム',       romaji: 'hamu',       meaning: 'ham' },
  { kana: 'ライス',     romaji: 'raisu',      meaning: 'rice (on a plate)' },
  { kana: 'アイス',     romaji: 'aisu',       meaning: 'ice cream' },
  { kana: 'ミント',     romaji: 'minto',      meaning: 'mint' },
  { kana: 'クリスマス', romaji: 'kurisumasu', meaning: 'Christmas' },
  { kana: 'ネクタイ',   romaji: 'nekutai',    meaning: 'necktie' },
  { kana: 'ハンカチ',   romaji: 'hankachi',   meaning: 'handkerchief' },
  { kana: 'ハンサム',   romaji: 'hansamu',    meaning: 'handsome' },
  { kana: 'テント',     romaji: 'tento',      meaning: 'tent' },
  { kana: 'ヒント',     romaji: 'hinto',      meaning: 'hint' },
  { kana: 'サイン',     romaji: 'sain',       meaning: 'a signature, a sign' },
  { kana: 'ライン',     romaji: 'rain',       meaning: 'line' },
  { kana: 'コイン',     romaji: 'koin',       meaning: 'coin' },
  { kana: 'ミス',       romaji: 'misu',       meaning: 'a mistake' },
  { kana: 'メモ',       romaji: 'memo',       meaning: 'a memo, a note' },
  { kana: 'キロ',       romaji: 'kiro',       meaning: 'kilo' },
  { kana: 'センチ',     romaji: 'senchi',     meaning: 'centimetre' },
  { kana: 'アメリカ',   romaji: 'amerika',    meaning: 'America' },
  { kana: 'イタリア',   romaji: 'itaria',     meaning: 'Italy' },
  { kana: 'フランス',   romaji: 'furansu',    meaning: 'France' },
  { kana: 'ロシア',     romaji: 'roshia',     meaning: 'Russia' },
  { kana: 'スイス',     romaji: 'suisu',      meaning: 'Switzerland' },
  { kana: 'アフリカ',   romaji: 'afurika',    meaning: 'Africa' },
  { kana: 'メキシコ',   romaji: 'mekishiko',  meaning: 'Mexico' },
  { kana: 'ハワイ',     romaji: 'hawai',      meaning: 'Hawaii' }
];
